# Generated by Django 5.2.15 on 2026-06-06 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("low", "Low")], default="high", max_length=10
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ui_run", "UI Run"),
                            ("ui_repl", "UI REPL"),
                            ("background_test", "Background Test"),
                            ("ai_analysis", "AI Analysis"),
                            ("webhook_ci", "Webhook CI"),
                        ],
                        default="ui_run",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("rejected", "Rejected"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_jobs",
                        to="files.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status", "priority", "queued_at"],
                        name="execution_e_user_id_2e9d8c_idx",
                    )
                ],
            },
        ),
    ]
