# Generated by Django 5.2.15 on 2026-06-06 09:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("path", models.CharField(max_length=1000)),
                ("content", models.TextField(blank=True, default="")),
                ("language", models.CharField(blank=True, default="", max_length=50)),
                ("yjs_state_version", models.PositiveIntegerField(default=0)),
                ("compaction_checkpoint_version", models.PositiveIntegerField(default=0)),
                ("yjs_snapshot", models.BinaryField(blank=True, null=True)),
                ("last_compacted_at", models.DateTimeField(blank=True, null=True)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="workspaces.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("branch_name", models.CharField(default="main", max_length=200)),
                ("snapshot", models.TextField()),
                ("snapshot_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto", "Auto"),
                            ("compaction", "Compaction"),
                            ("restore", "Restore"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="files.file",
                    ),
                ),
                (
                    "merge_base_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_children",
                        to="files.fileversion",
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="files.fileversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_branches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="files.file",
                    ),
                ),
                (
                    "created_from_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spawned_branches",
                        to="files.fileversion",
                    ),
                ),
                (
                    "head_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_heads",
                        to="files.fileversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MergeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("conflict_hunks", models.JSONField(default=list)),
                ("resolutions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_jobs",
                        to="files.fileversion",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_jobs",
                        to="files.file",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_merges",
                        to="files.filebranch",
                    ),
                ),
                (
                    "target_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_merges",
                        to="files.filebranch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operation_json", models.JSONField()),
                ("vector_clock", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="files.file",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["project", "path"], name="files_file_project_a9729f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("project", "path")},
        ),
        migrations.AddIndex(
            model_name="fileversion",
            index=models.Index(
                fields=["file", "-created_at"], name="files_filev_file_id_72365d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filebranch",
            unique_together={("file", "name")},
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["file", "vector_clock"], name="files_opera_file_id_5d5877_idx"
            ),
        ),
    ]
